version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finance_app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_SQL/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./init_SQL/update_db.sql:/docker-entrypoint-initdb.d/02-update.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./BE
    env_file:
      - ./BE/.env
    environment:
      DATABASE_URL: mysql+pymysql://root:password@db:3306/finance_app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./BE/src:/app/src

  frontend:
    build: ./FE
    env_file:
      - ./FE/.env
    ports:
      - "5174:5173"
    depends_on:
      - backend
    volumes:
      - ./FE/src:/app/src

volumes:
  db_data:
